### PR TITLE
- Use equals when comparing Optional<Long>

### LINKED ISSUE #28429: Using euclidean_distance with tensor<float>(d[128]) fails
Deploying with this schema works:
```
schema neighbors {
    document neighbors {
        field point type tensor<float>(d[127]) {
            indexing: attribute | summary
        }
    }
    rank-profile max_distance {
        inputs {
            query(qpoint) tensor<float>(d[127])
    }
        first-phase {
            expression {
                euclidean_distance(attribute(point), query(qpoint), d)
            }
        }
    }
}
```

Changing to 128 fails (deploying using fresh container):
```
schema neighbors {
    document neighbors {
        field point type tensor<float>(d[128]) {
            indexing: attribute | summary
        }
    }
    rank-profile max_distance {
        inputs {
            query(qpoint) tensor<float>(d[128])
    }
        first-phase {
            expression {
                euclidean_distance(attribute(point), query(qpoint), d)
            }
        }
    }
}
```

```
$ vespa deploy
Waiting up to 1m0s for deploy API...
Uploading application package... failed
Error: invalid application package (400 Bad Request)
Invalid application:
In schema 'neighbors', rank profile 'max_distance':
The first-phase expression is invalid:
euclidean_distance expects both arguments to have the 'd' dimension with same size, but input types were tensor<float>(d[128]) and tensor<float>(d[128])
```

No other files than services.xml in the application package:
```
$ cat services.xml 
<?xml version="1.0" encoding="UTF-8"?>
<services version="1.0">
    <container id="neighbors_container" version="1.0">
        <search></search>
        <document-api></document-api>
    </container>
    <content id="neighbors_content" version="1.0">
        <redundancy reply-after="1">1</redundancy>
        <documents>
            <document type="neighbors" mode="index"></document>
        </documents>
        <nodes>
            <node distribution-key="0" hostalias="node1"></node>
        </nodes>
    </content>
</services>
```

```
$ curl http://localhost:8080/state/v1/version
{
  "version" : "8.221.29"
```

I could not find a tensor size restriction in the documentation

### PR DESCRIPTION
**Pull request by baldersheim**
- Minor cleanup

@bratseth or @bjorncs or @arnej27959 PR
Should fix #28429

### CODE REVIEW

File: model-integration/src/main/java/ai/vespa/rankingexpression/importer/operations/Tile.java [hunk 1]
```diff
@@ -47,7 +47,7 @@ protected OrderedTensorType lazyGetType() {
             throw new IllegalArgumentException("Tile " + name + ": repeats must be a 1-d tensor.");
 
         OrderedTensorType inputType = inputs.get(0).type().get();
-        if (shape.type().dimensions().get(0).size().get() != inputType.rank())
```
Comment (bjorncs) [inline model-integration/src/main/java/ai/vespa/rankingexpression/importer/operations/Tile.java:50]: 🐛

**Review by bjorncs — APPROVED** [review]
