### PR TITLE
process all the summary fields with same name

### LINKED ISSUE #21733: Document summaries cannot contain predicates
**Describe the bug**
When a `summary` of type `predicate` is added to a `document-summary`, all queries fail (even those that do not request any `presentation.summary`).

**To Reproduce**
1. Used sample application [Predicate Search](https://github.com/vespa-engine/sample-apps/tree/master/examples/predicate-fields).
2. Added the following at line 20 to `src/main/application/schemas/ad.sd`:
````
  document-summary adsummary {
    from-disk
    summary title type string {
      source: title
    }
    summary target type predicate {
      source: target
    }
  }
````
3. After deploying and feeding data, the response to the application test is:
````
{
   "root":{
      "id":"toplevel",
      "relevance":1.0,
      "fields":{
         "totalCount":3
      },
      "coverage":{
         "coverage":100,
         "documents":4,
         "full":true,
         "nodes":1,
         "results":1,
         "resultsFull":1
      },
      "errors":[
         {
            "code":10,
            "summary":"Backend communication error",
            "message":"Error response from rpc node connection to vespa-container:19106: Connection error"
         }
      ],
      "children":[
         {
            "id":"index:adserver/0/85cecfac5cdb8b0c17bbe05c",
            "relevance":0.0017429193899782135,
            "source":"adserver"
         },
         {
            "id":"index:adserver/0/382f7509e4bed774eb3c57ee",
            "relevance":0.0017429193899782135,
            "source":"adserver"
         },
         {
            "id":"index:adserver/0/3e26ff81baa990bebf73395a",
            "relevance":0.0017429193899782135,
            "source":"adserver"
         }
      ]
   }
}
````

**Expected behavior**
````
{
   "root":{
      "id":"toplevel",
      "relevance":1.0,
      "fields":{
         "totalCount":3
      },
      "coverage":{
         "coverage":100,
         "documents":4,
         "full":true,
         "nodes":1,
         "results":1,
         "resultsFull":1
      },
      "children":[
         {
            "id":"id:sampleapp:ad::http://example.com/sled",
            "relevance":0.0017429193899782135,
            "source":"adserver",
            "fields":{
               "sddocname":"ad",
               "subqueries(target)":-1,
               "documentid":"id:sampleapp:ad::http://example.com/sled",
               "title":"ACME Rocket Sled",
               "target":"('name' in ['Wile E. Coyote'] or 'age' in [14..25])\n"
            }
         },
         {
            "id":"id:sampleapp:ad::http://example.com/boulder",
            "relevance":0.0017429193899782135,
            "source":"adserver",
            "fields":{
               "sddocname":"ad",
               "subqueries(target)":-1,
               "documentid":"id:sampleapp:ad::http://example.com/boulder",
               "title":"ACME Dehydrated Boulders",
               "target":"('name' in ['Wile E. Coyote'] or 'age' in [10..20])\n"
            }
         },
         {
            "id":"id:sampleapp:ad::http://example.com/tornado",
            "relevance":0.0017429193899782135,
            "source":"adserver",
            "fields":{
               "sddocname":"ad",
               "subqueries(target)":-1,
               "documentid":"id:sampleapp:ad::http://example.com/tornado",
               "title":"ACME Do-It Yourself Tornado Kit",
               "target":"('name' in ['Wile E. Coyote'] or 'age' in [20..40])\n"
            }
         }
      ]
   }
}
````

**Additional context**
Removing `target` from `adsummary` or adding any other new field of any other type yields the expected result.

### PR DESCRIPTION
**Pull request by arnej27959**
* we may have multiple instances of the "same" summary field when
  declared in document-summary blocks; ensure we process all of them.
* fixes: https://github.com/vespa-engine/vespa/issues/21733

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

@bjorncs or @bratseth please review

### CODE REVIEW

File: config-model/src/main/java/com/yahoo/searchdefinition/Schema.java [hunk 1]
```diff
@@ -584,21 +584,25 @@ public SummaryField getExplicitSummaryField(String name) {
...
-                                                                        : new java.util.LinkedHashMap<>();
+    public List<SummaryField> getSummaryFields(ImmutableSDField field) {
+        List<SummaryField> summaryFields = inherited.isPresent()
+            ? requireInherited().getSummaryFields(field)
+            : new java.util.ArrayList<>();
         for (DocumentSummary documentSummary : summaries.values()) {
             for (SummaryField summaryField : documentSummary.getSummaryFields().values()) {
                 if (summaryField.hasSource(field.getName())) {
-                    summaryFields.put(summaryField.getName(), summaryField);
+                    boolean wanted = true;
```
Comment (bratseth) [inline config-model/src/main/java/com/yahoo/searchdefinition/Schema.java:601]: L601 to 604 doesn't seem to do anything since `wanted` is never read?

Comment (arnej27959) [reply config-model/src/main/java/com/yahoo/searchdefinition/Schema.java:601]: oops, fixed. `wanted` is now used.

**Review by bratseth — APPROVED** [review]
